# Generated by Django 5.0.7 on 2024-09-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='group',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
