# Generated by Django 5.0.7 on 2024-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_enrollment_description_and_more'),
        ('payments', '0003_remove_paymentrecord_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('assignment', 'Asignación'), ('monthly', 'Mensualidad')], default='assignment', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('enrollment', 'payment_sequence')},
        ),
    ]
