# Generated by Django 5.0.7 on 2024-08-13 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_active_studentparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentparent',
            name='active',
        ),
        migrations.RemoveField(
            model_name='studentparent',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='studentparent',
            name='parent_phone',
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.parent'),
        ),
    ]
