# Generated by Django 5.0.7 on 2024-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_parent_remove_studentparent_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Maestro'), ('admin', 'Administrador')], default='student', max_length=10),
        ),
    ]
