# Generated by Django 5.0.7 on 2024-09-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_name_user_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='names',
            new_name='name',
        ),
    ]
