# Generated by Django 5.0.7 on 2024-09-07 13:41

import users.until
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.until.user_directory_path, validators=[users.until.validate_image]),
        ),
    ]
