# Generated by Django 5.0.7 on 2024-08-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['start_date'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='idCurso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='fin',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='año',
            new_name='hours_count',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='activo',
            new_name='in_person',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='presencial',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='visible',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='horario',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='inicio',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='profesor',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='cant_horas',
            new_name='year',
        ),
    ]
