# Generated by Django 5.0.7 on 2024-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_active_course_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa única de inscripción.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa mensual del curso.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_payments',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de pagos mensuales.', null=True),
        ),
    ]
