# Generated by Django 5.0.7 on 2024-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_enrollment_fee_course_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='description',
            field=models.CharField(default='Inscripción', max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
