# Generated by Django 5.0.7 on 2024-10-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_enrollment_description_enrollment_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='description',
            field=models.CharField(default='Asignación a Curso', max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
