# Generated by Django 5.0.7 on 2024-10-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_enrollment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='mount',
            new_name='amount',
        ),
    ]
