# Generated by Django 5.0.7 on 2024-10-21 20:12

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=assignments.models.submission_directory_path),
        ),
    ]
