# Generated by Django 5.0.7 on 2024-10-21 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_assignment_teacher_assignment_file_and_more'),
        ('courses', '0012_rename_mount_enrollment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
    ]
